name: polymer_vaadin_icons
version: 0.0.2
description: Vaadin icons to use in Polymer 1-2 components.
author: Dmitriy Vasilyev <kelegorm1@gmail.com>
homepage: https://github.com/kelegorm/dart-vaadin-icons